# Generated by Django 5.0.6 on 2024-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
